# Ejercicios
- Hacer un análisis general de los otros dos archivos CSV en ml-1m ('movies.dat' y 'ratings.dat')
- Analizando el dataset ratings.dat, ¿hay algún usuario que no tenga ninguna review? ¿Cuántos tienen menos de 30 reviews?

In [2]:
import numpy as np
import pandas as pd
import os

In [8]:
ruta_movies = os.path.join("res", "ml-1m", "movies.dat")
ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")
ruta_users=os.path.join("res", "ml-1m", "users.dat")
 
movies_dataset = pd.read_csv(ruta_movies, sep='::', index_col=0, engine='python',names=['ID','Nombre','Genero'])
display(movies_dataset.describe())

                  Nombre Genero
count               3883   3883
unique              3883    301
top     Toy Story (1995)  Drama
freq                   1    843

In [4]:
ratings_dataset = pd.read_csv(ruta_ratings, sep='::', engine='python',names=['UserID','MovieID','Rating','TimeStamp'])
display(ratings_dataset.describe())
display(ratings_dataset)

             UserID       MovieID        Rating     TimeStamp
count  1.000209e+06  1.000209e+06  1.000209e+06  1.000209e+06
mean   3.024512e+03  1.865540e+03  3.581564e+00  9.722437e+08
std    1.728413e+03  1.096041e+03  1.117102e+00  1.215256e+07
min    1.000000e+00  1.000000e+00  1.000000e+00  9.567039e+08
25%    1.506000e+03  1.030000e+03  3.000000e+00  9.653026e+08
50%    3.070000e+03  1.835000e+03  4.000000e+00  9.730180e+08
75%    4.476000e+03  2.770000e+03  4.000000e+00  9.752209e+08
max    6.040000e+03  3.952000e+03  5.000000e+00  1.046455e+09

         UserID  MovieID  Rating  TimeStamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [58]:
users_dataset=pd.read_csv(ruta_users, sep='::', index_col=0,engine='python',names=['UserID','Gender','Age','Occupation','Zip-code'])
users=users_dataset.index
users_ratings=ratings_dataset.groupby('UserID').size()
users_sin_reviews=pd.DataFrame(columns=['UserID'])
print(users)
print("--")
print(users_ratings)


for user in users_dataset.index:
    if user not in users_ratings:
        users_sin_reviews[user]

display(users_sin_reviews)

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040],
      dtype='int64', name='UserID', length=6040)
--
UserID
1        53
2       129
3        51
4        21
5       198
       ...
6036    888
6037    202
6038     20
6039    123
6040    341
Length: 6040, dtype: int64

Empty DataFrame
Columns: [UserID]
Index: []

In [50]:
users_ratings=ratings_dataset.groupby('UserID').size()
user_reviews=users_ratings[users_ratings<30]
print(user_reviews)

UserID
4       21
12      23
14      25
20      24
21      22
        ..
5983    28
5999    27
6012    23
6034    21
6038    20
Length: 751, dtype: int64